on:
  workflow_call:
    inputs:
      who-to-greet: 'Mona the Octocat'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: elblivion/update-codeowners@v1.1
        with:
          who-to-greet: {{ inputs.who-to-greet }}